package forge

import (
	"strings"
	"testing"
)

func TestCheckStamp_UpToDate(t *testing.T) {
	s := Stamp{Date: "2026-01-01", SHA: "abc1234def", Schema: 13, Template: 2}
	ok, msg := CheckStamp(s, "abc1234def", 2, "SKILL.md")
	if !ok {
		t.Fatalf("expected up to date, got stale with message: %s", msg)
	}
	if !strings.Contains(msg, "up to date") {
		t.Errorf("message = %q, want it to contain %q", msg, "up to date")
	}
}

func TestCheckStamp_RulesStale(t *testing.T) {
	s := Stamp{Date: "2026-01-01", SHA: "abc1234def", Schema: 13, Template: 2}
	ok, msg := CheckStamp(s, "def5678abc", 2, "SKILL.md")
	if ok {
		t.Fatal("expected stale when the rules SHA moved")
	}
	if !strings.Contains(msg, "abc1234") || !strings.Contains(msg, "def5678") {
		t.Errorf("message must name both SHAs, got: %s", msg)
	}
	if strings.Contains(msg, "template") {
		t.Errorf("rules-only staleness must not mention the template, got: %s", msg)
	}
	if !strings.Contains(msg, "regenerate: trustabl forge --output SKILL.md") {
		t.Errorf("message must carry the fix command, got: %s", msg)
	}
}

func TestCheckStamp_TemplateStale(t *testing.T) {
	s := Stamp{Date: "2026-01-01", SHA: "abc1234def", Schema: 13, Template: 1}
	ok, msg := CheckStamp(s, "abc1234def", 2, "SKILL.md")
	if ok {
		t.Fatal("expected stale when the template version is behind")
	}
	if !strings.Contains(msg, "template 1, current 2") {
		t.Errorf("message must name both template versions, got: %s", msg)
	}
	if !strings.Contains(msg, "rules are current") {
		t.Errorf("template-only staleness must say the rules are current, got: %s", msg)
	}
}

func TestCheckStamp_BothStale(t *testing.T) {
	s := Stamp{Date: "2026-01-01", SHA: "abc1234def", Schema: 13, Template: 1}
	ok, msg := CheckStamp(s, "def5678abc", 2, "SKILL.md")
	if ok {
		t.Fatal("expected stale when both moved")
	}
	if !strings.Contains(msg, "abc1234→def5678") {
		t.Errorf("message must show the SHA transition, got: %s", msg)
	}
	if !strings.Contains(msg, "template 1→2") {
		t.Errorf("message must show the template transition, got: %s", msg)
	}
}

func TestCheckStamp_NewerTemplateIsNotStale(t *testing.T) {
	// A file generated by a NEWER forge must not be reported stale by an
	// older binary — that would tell the user to downgrade their skill.
	s := Stamp{Date: "2026-01-01", SHA: "abc1234def", Schema: 13, Template: 5}
	ok, _ := CheckStamp(s, "abc1234def", 2, "SKILL.md")
	if !ok {
		t.Error("a newer template must not be reported as stale")
	}
}

func TestCheckStamp_MessageEndsInNewline(t *testing.T) {
	cases := []struct {
		name string
		s    Stamp
		sha  string
		tmpl int
	}{
		{"uptodate", Stamp{SHA: "a", Template: 2}, "a", 2},
		{"rules", Stamp{SHA: "a", Template: 2}, "b", 2},
		{"template", Stamp{SHA: "a", Template: 1}, "a", 2},
		{"both", Stamp{SHA: "a", Template: 1}, "b", 2},
	}
	for _, c := range cases {
		_, msg := CheckStamp(c.s, c.sha, c.tmpl, "SKILL.md")
		if !strings.HasSuffix(msg, "\n") {
			t.Errorf("%s: message must end in a newline, got %q", c.name, msg)
		}
	}
}
