package forge

import "fmt"

// CheckStamp compares a parsed stamp against the current rules SHA and
// template version, and returns whether the generated skill is current along
// with the message to print.
//
// It is deliberately pure — no filesystem, no rules resolution — so the
// comparison and its wording are unit-testable without network access.
//
// A stamp whose template is NEWER than this build's is not reported stale:
// an older binary must not tell the user to regenerate a file produced by a
// newer one. The returned message always ends in a newline.
func CheckStamp(stamp Stamp, currentSHA string, currentTemplate int, path string) (bool, string) {
	rulesStale := stamp.SHA != currentSHA
	templateStale := stamp.Template < currentTemplate

	switch {
	case !rulesStale && !templateStale:
		return true, fmt.Sprintf("up to date (rules: %s, generated: %s)\n",
			shortSHA(stamp.SHA), stamp.Date)

	case rulesStale && !templateStale:
		return false, fmt.Sprintf(
			"outdated: generated from %s, current rules are %s\n%s",
			shortSHA(stamp.SHA), shortSHA(currentSHA), regenerateHint(path))

	case !rulesStale && templateStale:
		return false, fmt.Sprintf(
			"outdated: generated by an older forge (template %d, current %d) — rules are current\n%s",
			stamp.Template, currentTemplate, regenerateHint(path))

	default:
		return false, fmt.Sprintf(
			"outdated: rules %s→%s and template %d→%d\n%s",
			shortSHA(stamp.SHA), shortSHA(currentSHA),
			stamp.Template, currentTemplate, regenerateHint(path))
	}
}

func regenerateHint(path string) string {
	return fmt.Sprintf("regenerate: trustabl forge --output %s\n", path)
}

// shortSHA returns the first 7 characters of a SHA for display, or the full
// string when it is shorter than 7 characters.
func shortSHA(sha string) string {
	if len(sha) < 7 {
		return sha
	}
	return sha[:7]
}
