package forge

// TemplateVersion is the version of the SKILL.md layout this build emits.
// It is stamped into generated files as the `template:` field and compared by
// `trustabl forge check`, which reports a file generated by an older template
// as outdated even when the rules SHA has not moved.
//
// This versions the GenerateCombined layout exclusively. Generate (the
// single-pack, skill-scope-only function kept for backward compatibility)
// emits neither the apply-loop section that defines version 2 nor the
// Runtime Tracing section that defines version 3, and has no production
// caller. Its golden fixture is stamped with the current TemplateVersion
// rather than kept in sync with what it actually emits.
//
// Forward-compatibility note: ParseStamp rejects a stamp with more than 5
// fields, so adding a 6th field to the stamp format will make an older
// binary report "no forge stamp found" for a file stamped by a newer one,
// rather than a clean version mismatch. Whoever adds the next field should
// account for this.
//
// Bump discipline — mirrors internal/rules/schema_version.go:
//
//   - Bump when the emitted STRUCTURE changes: a section added, removed, or
//     reordered, or a directive's meaning changed.
//   - Do NOT bump for typo fixes or wording polish.
//
// Every bump turns `forge check` red in every repo until the skill is
// regenerated. Bumping on prose tweaks trains users to ignore the signal,
// which destroys the check's value more thoroughly than not having it.
//
// History:
//
//	1 — original layout: header + per-SDK rule blocks.
//	2 — added the "How to Apply These Constraints" apply-loop section.
//	3 — added the "Runtime Tracing" section (OpenTelemetry + agent-reliability-otel-labels).
const TemplateVersion = 3
