package forge

// TemplateVersion is the version of the SKILL.md layout this build emits.
// It is stamped into generated files as the `template:` field and compared by
// `trustabl forge check`, which reports a file generated by an older template
// as outdated even when the rules SHA has not moved.
//
// Bump discipline — mirrors internal/rules/schema_version.go:
//
//   - Bump when the emitted STRUCTURE changes: a section added, removed, or
//     reordered, or a directive's meaning changed.
//   - Do NOT bump for typo fixes or wording polish.
//
// Every bump turns `forge check` red in every repo until the skill is
// regenerated. Bumping on prose tweaks trains users to ignore the signal,
// which destroys the check's value more thoroughly than not having it.
//
// History:
//
//	1 — original layout: header + per-SDK rule blocks.
//	2 — added the "How to Apply These Constraints" apply-loop section.
const TemplateVersion = 2
